package fr.lirmm.centileparsaisie;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2013-09-07T13:11:40.699+02:00
 * Generated source version: 2.7.6
 * 
 */
@WebService(targetNamespace = "http://centileparsaisie.lirmm.fr/", name = "CentileWS")
@XmlSeeAlso({ObjectFactory.class})
public interface CentileWS {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getCentile", targetNamespace = "http://centileparsaisie.lirmm.fr/", className = "fr.lirmm.centileparsaisie.GetCentile")
    @WebMethod
    @ResponseWrapper(localName = "getCentileResponse", targetNamespace = "http://centileparsaisie.lirmm.fr/", className = "fr.lirmm.centileparsaisie.GetCentileResponse")
    public java.lang.String getCentile(
        @WebParam(name = "valeursSaisies", targetNamespace = "")
        java.lang.String valeursSaisies,
        @WebParam(name = "percentile", targetNamespace = "")
        java.lang.String percentile
    );
}
