package fr.lirmm.centileparsaisie;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2013-09-07T13:11:40.779+02:00
 * Generated source version: 2.7.6
 * 
 */
@WebServiceClient(name = "CentileWSService", 
                  wsdlLocation = "CentileWSService.wsdl",
                  targetNamespace = "http://centileparsaisie.lirmm.fr/") 
public class CentileWSService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://centileparsaisie.lirmm.fr/", "CentileWSService");
    public final static QName CentileWSPort = new QName("http://centileparsaisie.lirmm.fr/", "CentileWSPort");
    static {
        URL url = CentileWSService.class.getResource("CentileWSService.wsdl");
        if (url == null) {
            url = CentileWSService.class.getClassLoader().getResource("CentileWSService.wsdl");
        } 
        if (url == null) {
            java.util.logging.Logger.getLogger(CentileWSService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "CentileWSService.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public CentileWSService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CentileWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CentileWSService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns CentileWS
     */
    @WebEndpoint(name = "CentileWSPort")
    public CentileWS getCentileWSPort() {
        return super.getPort(CentileWSPort, CentileWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CentileWS
     */
    @WebEndpoint(name = "CentileWSPort")
    public CentileWS getCentileWSPort(WebServiceFeature... features) {
        return super.getPort(CentileWSPort, CentileWS.class, features);
    }

}
